### ISSUE TITLE
Fix SQLite VACUUM INTO bug on macOS

### ISSUE THREAD

**Issue by shawnbrown** [shawnbrown/toron#2]
SQLite is raising an error when calling VACUUM INTO on empty files when running on the default GitHub-hosted macOS runner using CPython and PyPy versions 3.9 and 3.10.

### SQLite behavior

The SQLite docs are clear that this _should_ work (see [VACUUM with an INTO clause](https://www.sqlite.org/lang_vacuum.html#vacuum_with_an_into_clause)):

> The file named by the INTO clause must not previously exist, or else it must be an empty file, or the VACUUM INTO command will fail with an error. 

And it _does_ work, save for the cases mentioned here.

### Tox results on macOS

```text
py37: OK ✔ in 1 minute 12.36 seconds
py38: OK ✔ in 1 minute 12.45 seconds
py39: FAIL ✖ in 1 minute 46.46 seconds
pypy39: FAIL ✖ in 1 minute 46.29 seconds
py310: FAIL ✖ in 1 minute 45.97 seconds
pypy310: FAIL ✖ in 1 minute 45.55 seconds
py311: OK ✔ in 1 minute 12.42 seconds
py312: OK ✔ in 1 minute 13.37 seconds
py313: OK ✔ in 1 minute 11.48 seconds
```

The tests are all failing with the following error:

```text
======================================================================
ERROR: test_to_file (tests.data_access.test_data_connector.TestDataConnector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/toron/toron/tests/data_access/test_data_connector.py", line 185, in test_to_file
    connector.to_file(file_path, fsync=True)
  File "/Users/runner/work/toron/toron/.tox/.../site-packages/toron/_data_access/data_connector.py", line 298, in to_file
    cur.execute('VACUUM main INTO ?', (tmp_path,))
  File "/Users/runner/hostedtoolcache/.../_sqlite3.py", line 834, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/runner/hostedtoolcache/.../_sqlite3.py", line 995, in execute
    return self.__execute(False, sql, [params])
  File "/Users/runner/hostedtoolcache/.../_sqlite3.py", line 985, in __execute
    raise self.__connection._get_exception(ret)
_sqlite3.OperationalError: output file already exists
```

The error `sqlite3.OperationalError: output file already exists` should only be raised when the file is not empty. And I have verified that the file in question is, in fact, empty (contains 0 bytes) before and after the error is raised.

### GitHub-hosted runner software versions

Here are the versions of Python and SQLite that are currently used for testing:

| Runner | Tox Environment | Python Version | SQLite Version | Result |
| --- | --- | --- | :-: | :-: |
| macos-latest | py37 | 3.7.17 | 3.45.1 | OK |
| macos-latest | py38 | 3.8.18 | 3.45.1 | OK |
| **macos-latest** | **py39** | **3.9.18** | **3.37.0** | **FAIL** |
| **macos-latest** | **pypy39** | **3.9.18** | **3.37.0** | **FAIL** |
| **macos-latest** | **py310** | **3.10.13** | **3.37.0** | **FAIL**|
| **macos-latest** | **pypy310** | **3.10.13** | **3.37.0** | **FAIL** |
| macos-latest | py311 | 3.11.8 | 3.45.1 | OK |
| macos-latest | py312 | 3.12.2 | 3.45.1 | OK |
| macos-latest | py313 | 3.13.0 | 3.44.2 | OK |
| ubuntu-latest | py37 | 3.7.17 | 3.37.2 | OK |
| ubuntu-latest | py38 | 3.8.18 | 3.37.2 | OK |
| ubuntu-latest | py39 | 3.9.18 | 3.40.0 | OK |
| ubuntu-latest | pypy39 | 3.9.18 | 3.40.0 | OK |
| ubuntu-latest | py310 | 3.10.13 | 3.40.0 | OK|
| ubuntu-latest | pypy310 | 3.10.13 | 3.40.0 | OK |
| ubuntu-latest | py311 | 3.11.8 | 3.37.2 | OK |
| ubuntu-latest | py312 | 3.12.2 | 3.37.2 | OK |
| ubuntu-latest | py313 | 3.13.0 | 3.37.2 | OK |
| windows-latest | py37 | 3.7.9 | 3.31.1 | OK |
| windows-latest | py38 | 3.8.10 | 3.35.5 | OK |
| windows-latest | py39 | 3.9.13 | 3.37.2 | OK |
| windows-latest | pypy39 | 3.9.13 | 3.37.2 | OK |
| windows-latest | py310 | 3.10.13 | 3.40.1 | OK|
| windows-latest | pypy310 | 3.10.13 | 3.40.1 | OK |
| windows-latest | py311 | 3.11.8 | 3.43.1 | OK |
| windows-latest | py312 | 3.12.2 | 3.43.1 | OK |
| windows-latest | py313 | 3.13.0 | 3.44.2 | OK |

**Comment by shawnbrown** [comment]
This is resolved by commits 46d5696 and 561bfcd.
